[build]
  publish = "dist"
  command = "npm run build"
  functions = "dist/functions"
  [functions]
  # Sets a custom directory for Netlify Functions
  directory = "myfunctions/"
  node_bundler = "esbuild"
  # All functions
[functions]
  external_node_modules = ["module-one", "module-two"]

# Functions with a name starting with "my-function-*"
[functions."my-function-*"]
  external_node_modules = ["module-three", "module-four"]

# A function named "my-function-1"
[functions.my-function-1]
  external_node_modules = ["module-five", "module-six"]
  
  
  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  
  # Flags "package-1" as an external node module for all functions
  external_node_modules = ["package-1"]

[functions."api_*"]
  # Flags "package-2" as an external node module for functions with a name beginning with "api_".
  # Functions matching this pattern have both "package-1" and "package-2" as external modules,
  # because modules from this object are concatenated with any from the top-level object.
  external_node_modules = ["package-2"]

[functions.api_payment]
  # Flags "package-3" and "package-4" as external node modules for a function named "api_payment".
  # This function has 4 external node modules:
  #  "package-1" from the top-level object
  #  "package-2" from the "api_*" object
  #  "package-3" and "package-4" from this object
  external_node_modules = ["package-3", "package-4"]
[[redirects]]  
  from = "/add-tutorial/"
  to = "/tutorials/"
  
[[redirects]]
  from = "/post-1/"
  to = "/"
  
[[redirects]]
  from = "/post-2/"
  to = "/"
  
[[redirects]]
  from = "/post-3/"
  to = "/"
  
[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-minify-html"
